# Generated by Django 3.1.1 on 2023-06-20 07:00

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20230620_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=django.db.models.fields.Field.get_default, unique=True),
        ),
    ]
